spring.application.name=URLshortener

# Database
spring.datasource.url=${urlShortner_db_url}
# spring.datasource.url=jdbc:postgresql://ep-spring-breeze-ap1uih8u-pooler.c-7.us-east-1.aws.neon.tech/neondb?&sslmode=require&channelBinding=require
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${URLshortner_Database_Password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT
jwt.secret=${JWT_SECRET}